apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pythontest123
  janus-idp.io/tekton: pythontest123
  backstage.io/kubernetes-id: pythontest123
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pythontest123
resources: 
- deployment.yaml
- route.yaml
- service.yaml
