apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pythontest123
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pythontest123 
  name: pythontest123
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pythontest123 
